# Generated by Django 4.1.7 on 2023-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=10, unique=True)),
                ('location_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
